version: '3.4'

services:
  #Database settings
  catalogdb-mongo:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  basketdb-redis:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"


  #API settings
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017/CatalogDb"
    depends_on:
      - catalogdb-mongo
    ports:
      - "8000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__RedisConnectionString=basketdb:6379"
    depends_on:
      - basketdb-redis
    ports:
      - "8001:80"

    